import type { ProviderType } from "@/lib/provider-settings";

export type ProviderCategory = "official" | "aggregator" | "china" | "local" | "custom";

export interface ProviderPreset {
  id: string;
  label: string;
  type: ProviderType;
  baseUrl: string;
  defaultModel: string;
  apiKeyEnv?: string;
  requiresApiKey: boolean;
  category: ProviderCategory;
  description: string;
  docsUrl?: string;
}

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: "openai",
    label: "OpenAI",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4.1",
    apiKeyEnv: "OPENAI_API_KEY",
    requiresApiKey: true,
    category: "official",
    description: "Official OpenAI API.",
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    type: "openrouter",
    baseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "openai/gpt-5.5",
    apiKeyEnv: "OPENROUTER_API_KEY",
    requiresApiKey: true,
    category: "aggregator",
    description: "Access multiple model families through OpenRouter.",
    docsUrl: "https://openrouter.ai/docs",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    type: "deepseek",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-chat",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    requiresApiKey: true,
    category: "official",
    description: "DeepSeek OpenAI-compatible chat API.",
    docsUrl: "https://api-docs.deepseek.com",
  },
  {
    id: "mimo",
    label: "Xiaomi MiMo",
    type: "mimo",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    defaultModel: "mimo-v2.5-pro",
    apiKeyEnv: "MIMO_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "Xiaomi MiMo token-plan OpenAI-compatible endpoint.",
  },
  {
    id: "zhipu",
    label: "Zhipu GLM",
    type: "openai-compatible",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-4-flash",
    apiKeyEnv: "ZHIPU_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "Zhipu BigModel OpenAI-compatible API.",
    docsUrl: "https://docs.bigmodel.cn",
  },
  {
    id: "z-ai",
    label: "Z.ai GLM",
    type: "openai-compatible",
    baseUrl: "https://api.z.ai/api/paas/v4",
    defaultModel: "glm-4.5",
    apiKeyEnv: "ZAI_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "Z.ai global GLM OpenAI-compatible API.",
    docsUrl: "https://docs.z.ai",
  },
  {
    id: "moonshot",
    label: "Moonshot",
    type: "openai-compatible",
    baseUrl: "https://api.moonshot.cn/v1",
    defaultModel: "moonshot-v1-8k",
    apiKeyEnv: "MOONSHOT_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "Moonshot/Kimi OpenAI-compatible API.",
    docsUrl: "https://platform.moonshot.cn/docs",
  },
  {
    id: "minimax-cn",
    label: "MiniMax CN",
    type: "openai-compatible",
    baseUrl: "https://api.minimaxi.com/v1",
    defaultModel: "MiniMax-M1",
    apiKeyEnv: "MINIMAX_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "MiniMax China OpenAI-compatible endpoint.",
    docsUrl: "https://platform.minimaxi.com/docs",
  },
  {
    id: "minimax-global",
    label: "MiniMax Global",
    type: "openai-compatible",
    baseUrl: "https://api.minimax.io/v1",
    defaultModel: "MiniMax-M1",
    apiKeyEnv: "MINIMAX_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "MiniMax global OpenAI-compatible endpoint.",
    docsUrl: "https://platform.minimax.io/docs",
  },
  {
    id: "volcengine",
    label: "Volcengine Ark",
    type: "openai-compatible",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    defaultModel: "doubao-seed-1-6",
    apiKeyEnv: "ARK_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "ByteDance Volcengine Ark OpenAI-compatible endpoint.",
    docsUrl: "https://www.volcengine.com/docs/82379",
  },
  {
    id: "bailian",
    label: "Aliyun Bailian",
    type: "openai-compatible",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen-plus",
    apiKeyEnv: "DASHSCOPE_API_KEY",
    requiresApiKey: true,
    category: "china",
    description: "Alibaba Cloud DashScope OpenAI-compatible mode.",
    docsUrl: "https://help.aliyun.com/zh/model-studio",
  },
  {
    id: "mistral",
    label: "Mistral AI",
    type: "openai-compatible",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    apiKeyEnv: "MISTRAL_API_KEY",
    requiresApiKey: true,
    category: "official",
    description: "Mistral OpenAI-compatible chat API.",
    docsUrl: "https://docs.mistral.ai",
  },
  {
    id: "groq",
    label: "Groq",
    type: "openai-compatible",
    baseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    apiKeyEnv: "GROQ_API_KEY",
    requiresApiKey: true,
    category: "official",
    description: "Groq OpenAI-compatible inference API.",
    docsUrl: "https://console.groq.com/docs",
  },
  {
    id: "together",
    label: "Together AI",
    type: "openai-compatible",
    baseUrl: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    apiKeyEnv: "TOGETHER_API_KEY",
    requiresApiKey: true,
    category: "official",
    description: "Together AI OpenAI-compatible API.",
    docsUrl: "https://docs.together.ai",
  },
  {
    id: "ollama",
    label: "Ollama",
    type: "ollama",
    baseUrl: "http://localhost:11434/v1",
    defaultModel: "llama3.1",
    requiresApiKey: false,
    category: "local",
    description: "Local Ollama OpenAI-compatible endpoint.",
    docsUrl: "https://docs.ollama.com",
  },
  {
    id: "lmstudio",
    label: "LM Studio",
    type: "openai-compatible",
    baseUrl: "http://localhost:1234/v1",
    defaultModel: "lm-studio-default",
    requiresApiKey: false,
    category: "local",
    description: "LM Studio local OpenAI-compatible server.",
    docsUrl: "https://lmstudio.ai/docs",
  },
  {
    id: "litellm",
    label: "LiteLLM",
    type: "openai-compatible",
    baseUrl: "http://localhost:4000/v1",
    defaultModel: "gpt-4.1",
    apiKeyEnv: "LITELLM_API_KEY",
    requiresApiKey: false,
    category: "local",
    description: "LiteLLM local or remote proxy.",
    docsUrl: "https://docs.litellm.ai",
  },
  {
    id: "vllm",
    label: "vLLM",
    type: "openai-compatible",
    baseUrl: "http://localhost:8000/v1",
    defaultModel: "vllm-default",
    requiresApiKey: false,
    category: "local",
    description: "Self-hosted vLLM OpenAI-compatible server.",
    docsUrl: "https://docs.vllm.ai",
  },
  {
    id: "custom",
    label: "Custom API",
    type: "openai-compatible",
    baseUrl: "https://example.com/v1",
    defaultModel: "model-name",
    requiresApiKey: false,
    category: "custom",
    description: "Any OpenAI-compatible provider or proxy.",
  },
];

export function getProviderPreset(id?: string) {
  return PROVIDER_PRESETS.find((preset) => preset.id === id);
}

export function getProviderPresetByModel(model?: string) {
  if (!model) return undefined;
  return PROVIDER_PRESETS.find((preset) => preset.defaultModel === model);
}
