import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

interface RouteParams {
  params: Promise<{ id: string }>;
}

// Mock SCAD code generator based on parameters
function generateMockScadCode(parameterValues: Record<string, unknown>): string {
  const width = (parameterValues.width as number) ?? 40;
  const depth = (parameterValues.depth as number) ?? 30;
  const height = (parameterValues.height as number) ?? 15;
  const wallThickness = (parameterValues.wall_thickness as number) ?? 2.0;

  return `// Generated by AgentSCAD
// Part Family: electronics_enclosure
// Generated at: ${new Date().toISOString()}

wall_thickness = ${wallThickness};
width = ${width};
depth = ${depth};
height = ${height};

difference() {
  cube([width, depth, height], center=true);
  cube([width-2*wall_thickness, depth-2*wall_thickness, height-2*wall_thickness], center=true);
}`;
}

// Generate mock validation results
function generateMockValidationResults(wallThickness: number) {
  return [
    {
      rule_id: "R001",
      rule_name: "Minimum Wall Thickness",
      level: "ENGINEERING",
      passed: wallThickness >= 1.2,
      is_critical: true,
      message: `Wall thickness ${wallThickness}mm ${wallThickness >= 1.2 ? "meets" : "does not meet"} minimum 1.2mm`,
    },
    {
      rule_id: "R002",
      rule_name: "Maximum Dimensions",
      level: "MANUFACTURING",
      passed: true,
      is_critical: false,
      message: "All dimensions within manufacturing limits",
    },
    {
      rule_id: "R003",
      rule_name: "Manifold Geometry",
      level: "ENGINEERING",
      passed: true,
      is_critical: true,
      message: "Geometry is manifold (watertight)",
    },
    {
      rule_id: "S001",
      rule_name: "Semantic Geometry Match",
      level: "ENGINEERING",
      passed: true,
      is_critical: true,
      message: "Generated CAD matches the requested geometry",
    },
    {
      rule_id: "S002",
      rule_name: "Design Intent Preservation",
      level: "ENGINEERING",
      passed: true,
      is_critical: false,
      message: "Design intent preserved in generated model",
    },
  ];
}

// Helper to append execution log entries
function appendLog(existingLogs: string | null, event: string, message: string): string {
  let logs: Array<{ timestamp: string; event: string; message: string }> = [];
  if (existingLogs) {
    try {
      logs = JSON.parse(existingLogs);
    } catch {
      logs = [];
    }
  }
  logs.push({
    timestamp: new Date().toISOString(),
    event,
    message,
  });
  return JSON.stringify(logs);
}

// Delay helper for simulation
function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * POST /api/jobs/[id]/process
 * Start processing a job - simulate the orchestrator pipeline
 * Transitions: NEW → SCAD_GENERATED → RENDERED → VALIDATED → DELIVERED
 * Returns Server-Sent Events for progressive state updates
 */
export async function POST(
  _request: NextRequest,
  { params }: RouteParams
) {
  const { id } = await params;

  try {
    const job = await db.job.findUnique({ where: { id } });

    if (!job) {
      return NextResponse.json(
        { error: `Job not found with id: ${id}` },
        { status: 404 }
      );
    }

    // Only allow processing from NEW or failed states
    const processableStates = ["NEW", "VALIDATION_FAILED", "GEOMETRY_FAILED", "RENDER_FAILED", "HUMAN_REVIEW"];
    if (!processableStates.includes(job.state)) {
      return NextResponse.json(
        { error: `Job cannot be processed in state: ${job.state}. Must be in one of: ${processableStates.join(", ")}` },
        { status: 409 }
      );
    }

    // Use Server-Sent Events to stream progress
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        function sendEvent(data: Record<string, unknown>) {
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify(data)}\n\n`)
          );
        }

        try {
          // Parse parameter values for SCAD generation
          let paramValues: Record<string, unknown> = {};
          if (job.parameterValues) {
            try {
              paramValues = JSON.parse(job.parameterValues);
            } catch {
              paramValues = {};
            }
          }

          const wallThickness = (paramValues.wall_thickness as number) ?? 2.0;

          // Step 1: NEW → SCAD_GENERATED
          sendEvent({ state: "NEW", step: "starting", message: "Starting job processing pipeline..." });
          await delay(800);

          const scadCode = generateMockScadCode(paramValues);

          await db.job.update({
            where: { id },
            data: {
              state: "SCAD_GENERATED",
              scadSource: scadCode,
              builderName: "AgentSCAD-EnclosureBuilder",
              generationPath: "template_parametric",
              researchResult: JSON.stringify({
                references_found: 3,
                similar_designs: ["standard_box_enclosure_v1", "parametric_case_v2"],
                best_practices: ["Minimum wall thickness 1.2mm for FDM", "Add fillets for strength"],
              }),
              intentResult: JSON.stringify({
                geometry_type: "box_enclosure",
                features: ["hollow_interior", "uniform_walls"],
                constraints: ["printable_without_supports"],
              }),
              designResult: JSON.stringify({
                approach: "parametric_template",
                template_id: "electronics_enclosure_v1",
                parameters_mapped: Object.keys(paramValues),
              }),
              executionLogs: appendLog(job.executionLogs, "SCAD_GENERATED", "SCAD code generated successfully using parametric template"),
            },
          });

          sendEvent({
            state: "SCAD_GENERATED",
            step: "scad_generated",
            message: "SCAD code generated successfully",
            scadSource: scadCode,
          });
          await delay(1200);

          // Step 2: SCAD_GENERATED → RENDERED
          sendEvent({
            state: "SCAD_GENERATED",
            step: "rendering",
            message: "Rendering STL and preview image...",
          });
          await delay(1500);

          const mockStlPath = `/artifacts/${id}/stl`;
          const mockPngPath = `/artifacts/${id}/png`;

          await db.job.update({
            where: { id },
            data: {
              state: "RENDERED",
              stlPath: mockStlPath,
              pngPath: mockPngPath,
              renderLog: JSON.stringify({
                openscad_version: "2021.01",
                render_time_ms: 342,
                stl_triangles: 12,
                stl_vertices: 8,
                png_resolution: "800x600",
                warnings: [],
              }),
              executionLogs: appendLog(
                (await db.job.findUnique({ where: { id } }))?.executionLogs,
                "RENDERED",
                "STL and PNG rendered successfully (342ms render time)"
              ),
            },
          });

          sendEvent({
            state: "RENDERED",
            step: "rendered",
            message: "STL and PNG rendered successfully",
            stlPath: mockStlPath,
            pngPath: mockPngPath,
          });
          await delay(1000);

          // Step 3: RENDERED → VALIDATED
          sendEvent({
            state: "RENDERED",
            step: "validating",
            message: "Running validation rules...",
          });
          await delay(1200);

          const validationResults = generateMockValidationResults(wallThickness);

          await db.job.update({
            where: { id },
            data: {
              state: "VALIDATED",
              validationResults: JSON.stringify(validationResults),
              reportPath: `/artifacts/${id}/report`,
              executionLogs: appendLog(
                (await db.job.findUnique({ where: { id } }))?.executionLogs,
                "VALIDATED",
                `Validation passed: ${validationResults.filter((r) => r.passed).length}/${validationResults.length} rules passed`
              ),
            },
          });

          sendEvent({
            state: "VALIDATED",
            step: "validated",
            message: "Validation passed - all critical rules satisfied",
            validationResults,
          });
          await delay(800);

          // Step 4: VALIDATED → DELIVERED
          sendEvent({
            state: "VALIDATED",
            step: "delivering",
            message: "Preparing final deliverables...",
          });
          await delay(600);

          await db.job.update({
            where: { id },
            data: {
              state: "DELIVERED",
              completedAt: new Date(),
              executionLogs: appendLog(
                (await db.job.findUnique({ where: { id } }))?.executionLogs,
                "DELIVERED",
                "Job completed and deliverables ready"
              ),
            },
          });

          const finalJob = await db.job.findUnique({ where: { id } });

          sendEvent({
            state: "DELIVERED",
            step: "delivered",
            message: "Job completed successfully! All deliverables are ready.",
            job: finalJob,
          });

          controller.close();
        } catch (error) {
          console.error("Error during job processing:", error);

          // Update job state to indicate failure
          await db.job.update({
            where: { id },
            data: {
              state: "GEOMETRY_FAILED",
              executionLogs: appendLog(
                (await db.job.findUnique({ where: { id } }))?.executionLogs,
                "GEOMETRY_FAILED",
                `Processing failed: ${error instanceof Error ? error.message : "Unknown error"}`
              ),
            },
          });

          sendEvent({
            state: "GEOMETRY_FAILED",
            step: "error",
            message: `Processing failed: ${error instanceof Error ? error.message : "Unknown error"}`,
          });

          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (error) {
    console.error("Error starting job processing:", error);
    return NextResponse.json(
      { error: "Failed to start job processing" },
      { status: 500 }
    );
  }
}
