// Generated by AgentSCAD
// Part Family: spur_gear
// Generated at: 2026-04-23T20:19:09.474Z

teeth = 20;
outer_diameter = 50;
bore_diameter = 8;
thickness = 8;
pressure_angle = 20;

module spur_gear(teeth, outer_diameter, bore_diameter, thickness, pressure_angle) {
  tooth_module = outer_diameter / teeth;
  pitch_diameter = outer_diameter - 2 * tooth_module;
  tooth_depth = tooth_module * 2.2;

  difference() {
    union() {
      cylinder(h=thickness, d=outer_diameter, $fn=teeth, center=true);
      for (i = [0:teeth-1]) {
        rotate([0, 0, i * 360 / teeth])
          translate([pitch_diameter/2, 0, 0])
            cube([tooth_depth, tooth_module, thickness], center=true);
      }
    }
    cylinder(h=thickness+2, d=bore_diameter, $fn=64, center=true);
  }
}

spur_gear(teeth, outer_diameter, bore_diameter, thickness, pressure_angle);