import { db } from "@/lib/db";
import { broadcastWs } from "@/lib/ws-broadcast";
import { MIMO_DEFAULT_MODEL } from "@/lib/mimo";
import { appendLog, parameterDefsToValues } from "@/lib/stores/job-store";
import {
  detectPartFamily,
  getParameterSchema,
  runScadGenerationSkill,
} from "@/lib/harness/skill-runner";
import { buildRenderFailureLog, renderScadArtifacts } from "@/lib/tools/scad-renderer";
import {
  clearValidationCache,
  getCriticalValidationFailures,
  validateRenderedArtifacts,
} from "@/lib/tools/validation-tool";
import type {
  LLMGenerationResult,
  ParameterDef,
  PartFamily,
  RenderedArtifacts,
} from "@/lib/harness/types";

export type ProcessSseEvent = Record<string, unknown>;
export type ProcessEventSink = (data: ProcessSseEvent) => void;

export const PROCESSABLE_JOB_STATES = [
  "NEW",
  "DELIVERED",
  "VALIDATION_FAILED",
  "GEOMETRY_FAILED",
  "RENDER_FAILED",
  "HUMAN_REVIEW",
];

export function canProcessJobState(state: string): boolean {
  return PROCESSABLE_JOB_STATES.includes(state);
}

export function processableJobStatesMessage(): string {
  return PROCESSABLE_JOB_STATES.join(", ");
}

async function generateMockScadCode(
  inputRequest: string,
  parameterValues: Record<string, unknown>
): Promise<LLMGenerationResult> {
  const partFamily = detectPartFamily(inputRequest);
  const paramSchema = await getParameterSchema(partFamily, parameterValues);
  const ts = new Date().toISOString();

  const assignments = paramSchema
    .map((p) => {
      const val = p.kind === "integer" ? Math.round(p.value) : p.value;
      return `${p.key} = ${val};`;
    })
    .join("\n");

  let scadSource = "";
  let summary = "";

  switch (partFamily) {
    case "spur_gear": {
      const teeth = (parameterValues.teeth as number) ?? 20;
      const outerDiam = (parameterValues.outer_diameter as number) ?? 50;
      summary = `Spur gear with ${teeth} teeth, ${outerDiam}mm outer diameter`;
      scadSource = `// Generated by AgentSCAD
// Part Family: spur_gear
// Generated at: ${ts}

${assignments}

module spur_gear(teeth, outer_diameter, bore_diameter, thickness, pressure_angle) {
  tooth_module = outer_diameter / teeth;
  pitch_diameter = outer_diameter - 2 * tooth_module;
  tooth_depth = tooth_module * 2.2;

  difference() {
    union() {
      cylinder(h=thickness, d=outer_diameter, $fn=teeth, center=true);
      for (i = [0:teeth-1]) {
        rotate([0, 0, i * 360 / teeth])
          translate([pitch_diameter/2, 0, 0])
            cube([tooth_depth, tooth_module, thickness], center=true);
      }
    }
    cylinder(h=thickness+2, d=bore_diameter, $fn=64, center=true);
  }
}

spur_gear(teeth, outer_diameter, bore_diameter, thickness, pressure_angle);`;
      break;
    }

    case "device_stand": {
      const dw = (parameterValues.device_width as number) ?? 75;
      const sh = (parameterValues.stand_height as number) ?? 80;
      summary = `Device stand for ${dw}mm wide device, ${sh}mm tall`;
      scadSource = `// Generated by AgentSCAD
// Part Family: device_stand
// Generated at: ${ts}

${assignments}

module device_stand(device_width, device_depth, stand_height, lip_height,
                    wall_thickness, base_flare, arch_radius, arch_peak) {
  base_w = device_width + 2*wall_thickness + base_flare*2;
  base_d = device_depth + 2*wall_thickness + 30;

  translate([0, 0, wall_thickness/2])
    minkowski() {
      cube([base_w - 4, base_d - 4, wall_thickness - 1], center=true);
      cylinder(r=2, h=0.5, $fn=32);
    }

  translate([0, -base_d/2 + wall_thickness, stand_height/2])
    hull() {
      cube([device_width + 2*wall_thickness, wall_thickness, stand_height], center=true);
    }

  translate([0, device_depth/2 + wall_thickness, lip_height/2])
    cube([device_width + 2*wall_thickness, wall_thickness, lip_height], center=true);

  translate([arch_peak, -base_d/2 + wall_thickness*2, 0])
    cylinder(r=arch_radius, h=wall_thickness, $fn=64, center=true);
}

device_stand(device_width, device_depth, stand_height, lip_height,
             wall_thickness, base_flare, arch_radius, arch_peak);`;
      break;
    }

    case "phone_case": {
      const bl = (parameterValues.body_length as number) ?? 158;
      const bw = (parameterValues.body_width as number) ?? 78;
      const bd = (parameterValues.body_depth as number) ?? 8;
      summary = `Phone case for ${bl}×${bw}×${bd}mm device with camera opening, speaker holes, button cutouts, and charging port`;
      scadSource = `// Generated by AgentSCAD
// Part Family: phone_case
// Generated at: ${ts}

${assignments}

module phone_case(body_length, body_width, body_depth,
                  wall_thickness, camera_clearance) {
  outer_l = body_length + 2*wall_thickness;
  outer_w = body_width + 2*wall_thickness;
  outer_d = body_depth + wall_thickness;
  corner_r = 8;
  screen_margin = corner_r + 4;  // keep screen opening clear of rounded corners

  difference() {
    // Outer shell with rounded corners
    minkowski() {
      cube([outer_l - 2*corner_r, outer_w - 2*corner_r, outer_d - 1], center=true);
      cylinder(r=corner_r, h=0.5, $fn=64);
    }

    // Inner cavity for phone body
    translate([0, 0, wall_thickness])
      minkowski() {
        cube([body_length - 2*corner_r, body_width - 2*corner_r, body_depth + 0.5], center=true);
        cylinder(r=corner_r, h=0.5, $fn=64);
      }

    // Screen opening on front face
    translate([0, 0, outer_d/2 - 0.5])
      cube([body_length - 2*screen_margin, body_width - 2*screen_margin, wall_thickness + 3], center=true);

    // Camera cutout on rear face (top-left corner)
    translate([-body_length/2 + 18, -body_width/2 + 18, outer_d/2])
      cylinder(r=6 + camera_clearance, h=wall_thickness + 3, $fn=64);

    // Speaker grille holes through bottom edge
    for (spk = [-8, 0, 8]) {
      translate([body_length/2 - 20 + spk, body_width/2, 0]) rotate([90, 0, 0])
        cylinder(r=1, h=wall_thickness + 2, $fn=16, center=true);
    }

    // Charging port cutout (bottom edge, center)
    translate([body_length/2 - 10, body_width/2, 0])
      cube([8, wall_thickness + 2, 2.5], center=true);

    // Power button cutout (right side, upper area)
    translate([body_length/2, 0, body_depth * 0.3]) rotate([0, 90, 0])
      cylinder(r=4, h=wall_thickness + 2, $fn=32, center=true);

    // Volume button cutouts (left side)
    translate([-body_length/2, 0, body_depth * 0.3]) rotate([0, 90, 0])
      cylinder(r=2.5, h=wall_thickness + 2, $fn=32, center=true);
    translate([-body_length/2, 0, -body_depth * 0.1]) rotate([0, 90, 0])
      cylinder(r=2.5, h=wall_thickness + 2, $fn=32, center=true);
  }
}

phone_case(body_length, body_width, body_depth, wall_thickness, camera_clearance);`;
      break;
    }

    case "electronics_enclosure":
    default: {
      const w = (parameterValues.width as number) ?? 60;
      const d = (parameterValues.depth as number) ?? 40;
      const h = (parameterValues.height as number) ?? 25;
      const wt = (parameterValues.wall_thickness as number) ?? 2;
      summary = `Electronics enclosure ${w}×${d}×${h}mm, ${wt}mm walls`;
      scadSource = `// Generated by AgentSCAD
// Part Family: ${partFamily}
// Generated at: ${ts}

${assignments}

module enclosure_bottom(width, depth, height, wall_thickness,
                        corner_radius, clearance) {
  outer_w = width + 2*wall_thickness;
  outer_d = depth + 2*wall_thickness;
  outer_h = height + wall_thickness;

  difference() {
    minkowski() {
      cube([outer_w - 2*corner_radius, outer_d - 2*corner_radius, outer_h - corner_radius], center=true);
      cylinder(r=corner_radius, h=corner_radius, $fn=32);
    }
    translate([0, 0, wall_thickness/2])
      cube([width, depth, height + 1], center=true);
  }
}

module enclosure_lid(width, depth, wall_thickness, corner_radius, clearance) {
  lid_w = width + 2*wall_thickness - 2*clearance;
  lid_d = depth + 2*wall_thickness - 2*clearance;

  minkowski() {
    cube([lid_w - 2*corner_radius, lid_d - 2*corner_radius, wall_thickness - corner_radius], center=true);
    cylinder(r=corner_radius, h=corner_radius/2, $fn=32);
  }
}

enclosure_bottom(width, depth, height, wall_thickness, corner_radius, clearance);

translate([0, depth + 20, 0])
  enclosure_lid(width, depth, wall_thickness, corner_radius, clearance);`;
      break;
    }
  }

  return {
    summary,
    parameters: paramSchema,
    scad_source: scadSource,
  };
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function executeCadJob(jobId: string, sendEvent: ProcessEventSink) {
  const job = await db.job.findUnique({ where: { id: jobId } });
  if (!job) {
    throw new Error(`Job not found with id: ${jobId}`);
  }

  try {
    let paramValues: Record<string, unknown> = {};
    if (job.parameterValues) {
      try {
        paramValues = JSON.parse(job.parameterValues);
      } catch {
        paramValues = {};
      }
    }

    const wallThickness = (paramValues.wall_thickness as number) ?? 2.0;
    const inputRequest = job.inputRequest ?? "generic part";

    sendEvent({ state: "NEW", step: "starting", message: "Starting job processing pipeline..." });
    await delay(800);

    let generationResult: LLMGenerationResult;
    let usedLLM = false;

    try {
      sendEvent({
        state: "NEW",
        step: "generating_llm",
        message: `Generating SCAD code via ${job.modelId || process.env.MIMO_MODEL || MIMO_DEFAULT_MODEL}...`,
      });
      generationResult = await runScadGenerationSkill(inputRequest, paramValues, job.modelId);
      usedLLM = true;
    } catch (llmError) {
      const errMsg = llmError instanceof Error ? llmError.message : "Unknown LLM error";
      console.warn(`LLM generation failed, falling back to mock: ${errMsg}`);
      sendEvent({
        state: "NEW",
        step: "generating_mock",
        message: `LLM unavailable (${errMsg}), using template generation...`,
      });
      await delay(300);
      generationResult = await generateMockScadCode(inputRequest, paramValues);
    }

    const partFamily = detectPartFamily(inputRequest);
    const scadCode = generationResult.scad_source;
    const generationPath = usedLLM ? "llm_parametric" : "template_parametric";
    const builderName = usedLLM
      ? `AgentSCAD-LLM-${partFamily}`
      : `AgentSCAD-Template-${partFamily}`;

    await db.job.update({
      where: { id: jobId },
      data: {
        state: "SCAD_GENERATED",
        partFamily,
        scadSource: scadCode,
        builderName,
        generationPath,
        parameterSchema: JSON.stringify(generationResult.parameters),
        parameterValues: JSON.stringify(parameterDefsToValues(generationResult.parameters)),
        researchResult: JSON.stringify({
          part_family: partFamily,
          generation_method: usedLLM ? "llm" : "template",
          summary: generationResult.summary,
          references_found: usedLLM ? 0 : 3,
          similar_designs: usedLLM ? [] : ["standard_box_enclosure_v1", "parametric_case_v2"],
          best_practices: ["Minimum wall thickness 1.2mm for FDM", "Add fillets for strength"],
        }),
        intentResult: JSON.stringify({
          geometry_type: partFamily,
          features: ["parametric_design"],
          constraints: ["printable_without_supports"],
        }),
        designResult: JSON.stringify({
          approach: generationPath,
          model_id: job.modelId || process.env.MIMO_MODEL || MIMO_DEFAULT_MODEL,
          parameters_mapped: generationResult.parameters.map((p) => p.key),
          llm_used: usedLLM,
        }),
        executionLogs: appendLog(
          job.executionLogs,
          "SCAD_GENERATED",
          `SCAD code generated via ${usedLLM ? "LLM" : "template"} (family: ${partFamily})`
        ),
      },
    });

    sendEvent({
      state: "SCAD_GENERATED",
      step: "scad_generated",
      message: `SCAD code generated successfully via ${usedLLM ? "LLM" : "template"}`,
      scadSource: scadCode,
      parameters: generationResult.parameters,
      partFamily,
    });
    broadcastWs("job:update", { jobId, state: "SCAD_GENERATED", action: "scad_generated" }).catch(() => {});
    await delay(1200);

    sendEvent({
      state: "SCAD_GENERATED",
      step: "rendering",
      message: "Rendering STL and preview image with OpenSCAD...",
    });

    let warnings: string[] = [];
    let renderedArtifacts: RenderedArtifacts | null = null;

    try {
      sendEvent({ state: "SCAD_GENERATED", step: "rendering", message: "Generating STL..." });
      sendEvent({ state: "SCAD_GENERATED", step: "rendering", message: "Generating PNG preview..." });

      renderedArtifacts = await renderScadArtifacts(jobId, scadCode);
      clearValidationCache();
    } catch (execError) {
      const renderError =
        execError instanceof Error ? execError.message : "Unknown OpenSCAD render error";
      warnings.push(`OpenSCAD rendering failed: ${renderError}`);

      console.warn("OpenSCAD rendering failed:", execError);

      await db.job.update({
        where: { id: jobId },
        data: {
          state: "GEOMETRY_FAILED",
          renderLog: JSON.stringify(buildRenderFailureLog(0, warnings)),
          executionLogs: appendLog(
            (await db.job.findUnique({ where: { id: jobId } }))?.executionLogs,
            "GEOMETRY_FAILED",
            `OpenSCAD render failed: ${renderError}`
          ),
        },
      });

      sendEvent({
        state: "GEOMETRY_FAILED",
        step: "render_failed",
        message: "OpenSCAD render failed. Real STL/PNG artifacts were not generated.",
        error: renderError,
      });
      broadcastWs("job:update", { jobId, state: "GEOMETRY_FAILED", action: "render_failed" }).catch(() => {});
      return;
    }

    if (!renderedArtifacts) {
      throw new Error("OpenSCAD render did not return artifact paths");
    }

    await db.job.update({
      where: { id: jobId },
      data: {
        state: "RENDERED",
        stlPath: renderedArtifacts.stlPath,
        pngPath: renderedArtifacts.pngPath,
        renderLog: JSON.stringify(renderedArtifacts.renderLog),
        executionLogs: appendLog(
          (await db.job.findUnique({ where: { id: jobId } }))?.executionLogs,
          "RENDERED",
          `STL and PNG rendered successfully (${renderedArtifacts.renderLog.render_time_ms}ms)`
        ),
      },
    });

    sendEvent({
      state: "RENDERED",
      step: "rendered",
      message: "STL and PNG rendered successfully",
      stlPath: renderedArtifacts.stlPath,
      pngPath: renderedArtifacts.pngPath,
    });
    broadcastWs("job:update", { jobId, state: "RENDERED", action: "rendered" }).catch(() => {});
    await delay(1000);

    sendEvent({
      state: "RENDERED",
      step: "validating",
      message: "Running validation rules...",
    });
    await delay(1200);

    const validationResults = await validateRenderedArtifacts({
      inputRequest,
      partFamily,
      scadSource: scadCode,
      stlFilePath: renderedArtifacts.stlFilePath,
      previewImagePath: renderedArtifacts.pngFilePath,
      wallThickness,
    });
    const criticalFailures = getCriticalValidationFailures(validationResults);

    if (criticalFailures.length > 0) {
      await db.job.update({
        where: { id: jobId },
        data: {
          state: "HUMAN_REVIEW",
          validationResults: JSON.stringify(validationResults),
          reportPath: `/artifacts/${jobId}/report`,
          executionLogs: appendLog(
            (await db.job.findUnique({ where: { id: jobId } }))?.executionLogs,
            "HUMAN_REVIEW",
            `Rendered artifacts kept for review; validation blockers: ${criticalFailures.map((rule) => `${rule.rule_id} ${rule.rule_name}`).join(", ")}`
          ),
        },
      });

      sendEvent({
        state: "HUMAN_REVIEW",
        step: "validation_failed",
        message: "Rendered successfully; validation blockers require review or repair before export",
        validationResults,
      });
      broadcastWs("job:update", { jobId, state: "HUMAN_REVIEW", action: "validation_review" }).catch(() => {});
      return;
    }

    await db.job.update({
      where: { id: jobId },
      data: {
        state: "VALIDATED",
        validationResults: JSON.stringify(validationResults),
        reportPath: `/artifacts/${jobId}/report`,
        executionLogs: appendLog(
          (await db.job.findUnique({ where: { id: jobId } }))?.executionLogs,
          "VALIDATED",
          (() => {
            const actionable = validationResults.filter((r) => !r.message.toLowerCase().startsWith("skipped"));
            const skipped = validationResults.length - actionable.length;
            return `Validation passed: ${actionable.filter((r) => r.passed).length}/${actionable.length} actionable rules passed` +
              (skipped > 0 ? `, ${skipped} skipped` : " [real mesh analysis]");
          })()
        ),
      },
    });

    sendEvent({
      state: "VALIDATED",
      step: "validated",
      message: "Validation passed - all critical rules satisfied",
      validationResults,
    });
    broadcastWs("job:update", { jobId, state: "VALIDATED", action: "validated" }).catch(() => {});
    await delay(800);

    sendEvent({
      state: "VALIDATED",
      step: "delivering",
      message: "Preparing final deliverables...",
    });
    await delay(600);

    await db.job.update({
      where: { id: jobId },
      data: {
        state: "DELIVERED",
        completedAt: new Date(),
        executionLogs: appendLog(
          (await db.job.findUnique({ where: { id: jobId } }))?.executionLogs,
          "DELIVERED",
          "Job completed and deliverables ready"
        ),
      },
    });

    const finalJob = await db.job.findUnique({ where: { id: jobId } });

    sendEvent({
      state: "DELIVERED",
      step: "delivered",
      message: "Job completed successfully! All deliverables are ready.",
      job: finalJob,
    });
    broadcastWs("job:update", { jobId, state: "DELIVERED", action: "delivered" }).catch(() => {});
  } catch (error) {
    console.error("Error during job processing:", error);

    const message = error instanceof Error ? error.message : "Unknown error";

    await db.job.update({
      where: { id: jobId },
      data: {
        state: "GEOMETRY_FAILED",
        executionLogs: appendLog(
          (await db.job.findUnique({ where: { id: jobId } }))?.executionLogs,
          "GEOMETRY_FAILED",
          `Processing failed: ${message}`
        ),
      },
    });

    sendEvent({
      state: "GEOMETRY_FAILED",
      step: "error",
      message: `Processing failed: ${message}`,
    });
    broadcastWs("job:update", { jobId, state: "GEOMETRY_FAILED", action: "error" }).catch(() => {});
  }
}
