import { NextResponse } from "next/server";

export interface ModelInfo {
  id: string;
  name: string;
  description: string;
  provider: string;
  providerName: string;
  multimodal: boolean;
  reasoning: boolean;
  category: "flagship" | "fast" | "reasoning" | "vision" | "code";
}

const AVAILABLE_MODELS: ModelInfo[] = [
  // ─── OpenAI ──────────────────────────────────────────────────────────────
  {
    id: "gpt-4o",
    name: "GPT-4o",
    description: "OpenAI旗舰多模态模型，支持文本和图像理解",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: false,
    category: "flagship",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    description: "OpenAI轻量级多模态模型，速度快成本低",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: false,
    category: "fast",
  },
  {
    id: "o1",
    name: "o1",
    description: "OpenAI高级推理模型，适合复杂问题求解",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: false,
    reasoning: true,
    category: "reasoning",
  },
  {
    id: "o1-mini",
    name: "o1 Mini",
    description: "OpenAI轻量推理模型，平衡速度与推理能力",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: false,
    reasoning: true,
    category: "reasoning",
  },
  {
    id: "o3-mini",
    name: "o3 Mini",
    description: "OpenAI最新推理模型，更高效的推理能力",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: false,
    reasoning: true,
    category: "reasoning",
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    description: "OpenAI最新GPT-4.1，增强指令遵循和编码能力",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: false,
    category: "flagship",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    description: "GPT-4.1轻量版，更快响应速度",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: false,
    category: "fast",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    description: "GPT-4.1超轻量版，最低延迟和成本",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: false,
    reasoning: false,
    category: "fast",
  },

  // ─── Anthropic ───────────────────────────────────────────────────────────
  {
    id: "claude-sonnet-4-20250514",
    name: "Claude Sonnet 4",
    description: "Anthropic最新Sonnet，平衡性能与速度",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: true,
    category: "flagship",
  },
  {
    id: "claude-opus-4-20250514",
    name: "Claude Opus 4",
    description: "Anthropic最强编码模型，适合复杂长时间任务",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: true,
    category: "reasoning",
  },
  {
    id: "claude-3-5-sonnet-20241022",
    name: "Claude 3.5 Sonnet",
    description: "Anthropic经典高性能模型，广泛使用",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: false,
    category: "flagship",
  },
  {
    id: "claude-3-5-haiku-20241022",
    name: "Claude 3.5 Haiku",
    description: "Anthropic快速模型，低延迟高吞吐",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: false,
    category: "fast",
  },

  // ─── Google Gemini ───────────────────────────────────────────────────────
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    description: "Google最强推理模型，思考型AI",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: true,
    category: "reasoning",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    description: "Google快速推理模型，速度与智能兼顾",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: true,
    category: "fast",
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    description: "Google最轻量2.5模型，极速低耗",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: false,
    category: "fast",
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    description: "Google 2.0快速多模态模型",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: false,
    category: "fast",
  },

  // ─── DeepSeek ────────────────────────────────────────────────────────────
  {
    id: "deepseek-chat",
    name: "DeepSeek-V3",
    description: "DeepSeek旗舰对话模型，671B MoE架构",
    provider: "deepseek",
    providerName: "DeepSeek",
    multimodal: false,
    reasoning: false,
    category: "flagship",
  },
  {
    id: "deepseek-reasoner",
    name: "DeepSeek-R1",
    description: "DeepSeek推理模型，强化推理与数学能力",
    provider: "deepseek",
    providerName: "DeepSeek",
    multimodal: false,
    reasoning: true,
    category: "reasoning",
  },

  // ─── Zhipu / GLM ─────────────────────────────────────────────────────────
  {
    id: "glm-4",
    name: "GLM-4",
    description: "智谱GLM-4高性能文本模型",
    provider: "zhipu",
    providerName: "智谱AI",
    multimodal: false,
    reasoning: false,
    category: "flagship",
  },
  {
    id: "glm-4v",
    name: "GLM-4V",
    description: "智谱GLM-4V原生多模态模型（支持图像理解）",
    provider: "zhipu",
    providerName: "智谱AI",
    multimodal: true,
    reasoning: false,
    category: "vision",
  },
  {
    id: "glm-4-flash",
    name: "GLM-4 Flash",
    description: "智谱GLM-4快速版，低延迟",
    provider: "zhipu",
    providerName: "智谱AI",
    multimodal: false,
    reasoning: false,
    category: "fast",
  },

  // ─── Qwen / Alibaba ─────────────────────────────────────────────────────
  {
    id: "qwen-max",
    name: "Qwen Max",
    description: "阿里通义千问旗舰模型，最强推理能力",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: false,
    reasoning: false,
    category: "flagship",
  },
  {
    id: "qwen-plus",
    name: "Qwen Plus",
    description: "阿里通义千问增强模型，平衡性能与成本",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: false,
    reasoning: false,
    category: "fast",
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    description: "阿里通义千问极速模型，最低延迟",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: false,
    reasoning: false,
    category: "fast",
  },
  {
    id: "qwen-vl-max",
    name: "Qwen VL Max",
    description: "通义千问视觉旗舰模型，图像理解",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: true,
    reasoning: false,
    category: "vision",
  },

  // ─── Mistral ─────────────────────────────────────────────────────────────
  {
    id: "mistral-large-latest",
    name: "Mistral Large",
    description: "Mistral旗舰模型，顶级推理能力",
    provider: "mistral",
    providerName: "Mistral AI",
    multimodal: false,
    reasoning: false,
    category: "flagship",
  },
  {
    id: "mistral-small-latest",
    name: "Mistral Small",
    description: "Mistral轻量模型，快速高效",
    provider: "mistral",
    providerName: "Mistral AI",
    multimodal: false,
    reasoning: false,
    category: "fast",
  },
  {
    id: "codestral-latest",
    name: "Codestral",
    description: "Mistral代码专用模型，22B参数",
    provider: "mistral",
    providerName: "Mistral AI",
    multimodal: false,
    reasoning: false,
    category: "code",
  },
];

export async function GET() {
  return NextResponse.json({ models: AVAILABLE_MODELS });
}
