import { NextResponse } from "next/server";

export interface ModelInfo {
  id: string;
  name: string;
  description: string;
  provider: string;
  providerName: string;
  multimodal: boolean;
  reasoning: boolean;
  category: "flagship" | "fast" | "reasoning" | "vision" | "code";
  released?: string;
  deprecated?: boolean;
}

// ─── 2026 Latest AI Model Matrix ──────────────────────────────────────────
// Updated April 2026 based on official API documentation verification
// Sources: developers.openai.com, platform.claude.com, ai.google.dev,
//          api-docs.deepseek.com, bigmodel.cn, alibabacloud.com

const AVAILABLE_MODELS: ModelInfo[] = [
  // ─── Xiaomi MiMo ─────────────────────────────────────────────────────────
  {
    id: "mimo-v2.5",
    name: "MiMo-V2.5",
    description: "Xiaomi MiMo native multimodal model for fast general agent tasks.",
    provider: "mimo",
    providerName: "Xiaomi MiMo",
    multimodal: true,
    reasoning: true,
    category: "vision",
    released: "2026-04",
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo-V2.5-Pro",
    description: "Xiaomi MiMo OpenAI-compatible default model.",
    provider: "mimo",
    providerName: "Xiaomi MiMo",
    multimodal: false,
    reasoning: true,
    category: "flagship",
    released: "2026-04",
  },
  {
    id: "mimo-v2-omni",
    name: "MiMo-V2-Omni",
    description: "Xiaomi MiMo legacy full-modal model for image, audio, and video turns.",
    provider: "mimo",
    providerName: "Xiaomi MiMo",
    multimodal: true,
    reasoning: true,
    category: "vision",
    released: "2025-12",
  },

  // ─── OpenAI ──────────────────────────────────────────────────────────────
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    description: "OpenAI最新GPT-4.1，增强指令遵循和编码能力，支持长上下文",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: false,
    category: "flagship",
    released: "2025-03",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    description: "GPT-4.1轻量版，更快响应速度，高性价比",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: false,
    category: "fast",
    released: "2025-03",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    description: "GPT-4.1超轻量版，最低延迟和成本，适合端侧部署",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: false,
    reasoning: false,
    category: "fast",
    released: "2025-03",
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    description: "OpenAI旗舰GPT-5，最强推理与编码能力，内置推理",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: true,
    category: "flagship",
    released: "2025-07",
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    description: "GPT-5轻量版，推理能力强，速度与成本兼顾",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: true,
    category: "fast",
    released: "2025-09",
  },
  {
    id: "o3",
    name: "o3",
    description: "OpenAI高级推理模型，强化思维链推理，适合复杂问题",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: false,
    reasoning: true,
    category: "reasoning",
    released: "2025-04",
  },
  {
    id: "o4-mini",
    name: "o4 Mini",
    description: "OpenAI最新轻量推理模型，高效推理能力",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: true,
    category: "reasoning",
    released: "2025-06",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    description: "OpenAI经典多模态模型（已被GPT-4.1替代，仍可使用）",
    provider: "openai",
    providerName: "OpenAI",
    multimodal: true,
    reasoning: false,
    category: "flagship",
    released: "2024-05",
    deprecated: true,
  },

  // ─── Anthropic ───────────────────────────────────────────────────────────
  {
    id: "claude-opus-4-7-20260401",
    name: "Claude Opus 4.7",
    description: "Anthropic最强模型，视觉理解和代理能力极强，支持1M上下文",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: true,
    category: "flagship",
    released: "2026-04",
  },
  {
    id: "claude-opus-4-6-20260205",
    name: "Claude Opus 4.6",
    description: "Anthropic高可靠编码模型，适合复杂长时间任务",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: true,
    category: "reasoning",
    released: "2026-02",
  },
  {
    id: "claude-sonnet-4-6-20260217",
    name: "Claude Sonnet 4.6",
    description: "Anthropic最新Sonnet，编码/智能体/推理全面升级",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: true,
    category: "flagship",
    released: "2026-02",
  },
  {
    id: "claude-sonnet-4-5-20251022",
    name: "Claude Sonnet 4.5",
    description: "Anthropic经典高性能模型，广泛使用",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: true,
    category: "flagship",
    released: "2025-10",
  },
  {
    id: "claude-haiku-4-5-20251022",
    name: "Claude Haiku 4.5",
    description: "Anthropic快速模型，极速响应，低延迟高吞吐",
    provider: "anthropic",
    providerName: "Anthropic",
    multimodal: true,
    reasoning: false,
    category: "fast",
    released: "2025-10",
  },

  // ─── Google Gemini ───────────────────────────────────────────────────────
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    description: "Google最强推理模型，复杂任务首选，1M上下文",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: true,
    category: "flagship",
    released: "2026-02",
  },
  {
    id: "gemini-3.1-flash",
    name: "Gemini 3.1 Flash",
    description: "Google最新快速推理模型，速度与智能兼顾，含TTS增强",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: true,
    category: "fast",
    released: "2026-03",
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    description: "Google 3.0快速多模态模型，1M上下文，高效推理",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: true,
    category: "fast",
    released: "2025-12",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    description: "Google思考型AI（已被3.1替代，仍可使用）",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: true,
    category: "reasoning",
    released: "2025-03",
    deprecated: true,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    description: "Google快速推理模型（已被3.1替代，仍可使用）",
    provider: "google",
    providerName: "Google",
    multimodal: true,
    reasoning: true,
    category: "fast",
    released: "2025-05",
    deprecated: true,
  },

  // ─── DeepSeek ────────────────────────────────────────────────────────────
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    description: "DeepSeek V4 Pro 推理增强模型，适合复杂 CAD/OpenSCAD 生成。",
    provider: "deepseek",
    providerName: "DeepSeek",
    multimodal: false,
    reasoning: true,
    category: "reasoning",
    released: "2026-04",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    description: "DeepSeek V4 Flash 快速模型，适合低延迟 CAD 草稿生成。",
    provider: "deepseek",
    providerName: "DeepSeek",
    multimodal: false,
    reasoning: true,
    category: "fast",
    released: "2026-04",
  },
  {
    id: "deepseek-chat",
    name: "DeepSeek-V3",
    description: "DeepSeek旗舰对话模型，671B MoE架构，性价比极高",
    provider: "deepseek",
    providerName: "DeepSeek",
    multimodal: false,
    reasoning: false,
    category: "flagship",
    released: "2024-12",
  },
  {
    id: "deepseek-reasoner",
    name: "DeepSeek-R1",
    description: "DeepSeek推理模型，强化推理与数学能力，对标o1",
    provider: "deepseek",
    providerName: "DeepSeek",
    multimodal: false,
    reasoning: true,
    category: "reasoning",
    released: "2025-01",
  },

  // ─── Zhipu / GLM ─────────────────────────────────────────────────────────
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    description: "智谱最新旗舰，744B MoE，编码对标GPT-5级别，可持续工作8小时",
    provider: "zhipu",
    providerName: "智谱AI",
    multimodal: true,
    reasoning: true,
    category: "flagship",
    released: "2026-04",
  },
  {
    id: "glm-5-turbo",
    name: "GLM-5 Turbo",
    description: "智谱GLM-5加速版，更快响应，适合日常任务",
    provider: "zhipu",
    providerName: "智谱AI",
    multimodal: true,
    reasoning: false,
    category: "fast",
    released: "2026-03",
  },
  {
    id: "glm-4v-plus",
    name: "GLM-4V-Plus",
    description: "智谱增强版视觉模型，图像理解能力更强",
    provider: "zhipu",
    providerName: "智谱AI",
    multimodal: true,
    reasoning: false,
    category: "vision",
    released: "2025-09",
  },
  {
    id: "glm-4-flash",
    name: "GLM-4 Flash",
    description: "智谱高效免费/低价模型，极速响应",
    provider: "zhipu",
    providerName: "智谱AI",
    multimodal: false,
    reasoning: false,
    category: "fast",
    released: "2024-06",
  },

  // ─── Qwen / Alibaba ─────────────────────────────────────────────────────
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    description: "阿里通义千问最强旗舰模型，复杂任务首选",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: false,
    reasoning: true,
    category: "flagship",
    released: "2025-12",
  },
  {
    id: "qwen3.5-plus",
    name: "Qwen3.5 Plus",
    description: "阿里最新增强版，文本媲美Qwen3-Max，多模态增强",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: true,
    reasoning: false,
    category: "fast",
    released: "2026-01",
  },
  {
    id: "qwen3-vl",
    name: "Qwen3 VL",
    description: "通义千问视觉旗舰模型，图像理解与交互",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: true,
    reasoning: false,
    category: "vision",
    released: "2025-11",
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    description: "阿里通义千问极速模型，最低延迟",
    provider: "qwen",
    providerName: "阿里云",
    multimodal: false,
    reasoning: false,
    category: "fast",
    released: "2024-06",
  },

  // ─── Mistral ─────────────────────────────────────────────────────────────
  {
    id: "mistral-large-latest",
    name: "Mistral Large",
    description: "Mistral旗舰模型，顶级推理能力",
    provider: "mistral",
    providerName: "Mistral AI",
    multimodal: false,
    reasoning: false,
    category: "flagship",
    released: "2025-02",
  },
  {
    id: "mistral-small-latest",
    name: "Mistral Small",
    description: "Mistral轻量模型，快速高效",
    provider: "mistral",
    providerName: "Mistral AI",
    multimodal: false,
    reasoning: false,
    category: "fast",
    released: "2025-02",
  },
  {
    id: "codestral-latest",
    name: "Codestral",
    description: "Mistral代码专用模型，22B参数，编码专精",
    provider: "mistral",
    providerName: "Mistral AI",
    multimodal: false,
    reasoning: false,
    category: "code",
    released: "2024-05",
  },
];

export async function GET() {
  return NextResponse.json({ models: AVAILABLE_MODELS });
}
